version: '3'
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    
  flask_app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - OLLAMA_API_URL=http://ollama:11434
    depends_on:
      - ollama
    command: >
      /bin/bash -c "sleep 10; /app/setup_models.sh; python app.py"
